---
kind: pipeline
type: docker
name: pr-lint

# Lint PR titles and commits for conventional commits format
trigger:
  event:
    - pull_request

steps:
  - name: install-dependencies
    image: node:20-alpine
    commands:
      - npm ci --only=dev

  - name: lint-pr-title
    image: node:20-alpine
    commands:
      - |
        echo "Validating PR title: ${DRONE_PULL_REQUEST_TITLE}"
        echo "${DRONE_PULL_REQUEST_TITLE}" | npx commitlint --verbose
    when:
      event:
        - pull_request

  - name: lint-commits
    image: node:20-alpine
    commands:
      - |
        echo "Linting commits in PR..."
        # Get all commits in the PR
        apk add --no-cache git
        git fetch origin ${DRONE_COMMIT_BRANCH}
        git fetch origin ${DRONE_TARGET_BRANCH}
        # Lint each commit message
        npx commitlint --from origin/${DRONE_TARGET_BRANCH} --to HEAD --verbose
    when:
      event:
        - pull_request

  - name: check-conventional-commits
    image: alpine:latest
    commands:
      - |
        echo "✅ All commits follow conventional commits format"
        echo "PR Title: ${DRONE_PULL_REQUEST_TITLE}"
        echo "Valid commit types: feat, fix, docs, style, refactor, perf, test, chore, ci, revert"
    when:
      event:
        - pull_request

  - name: notify-lint-failure
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_chat_id
      message: |
        ❌ PR Lint Failed!

        PR: #${DRONE_PULL_REQUEST}
        Title: ${DRONE_PULL_REQUEST_TITLE}
        Author: {{ commit.author }}

        Please ensure PR title and commits follow conventional commits format.
    when:
      status:
        - failure
      event:
        - pull_request
