---
kind: pipeline
type: docker
name: pr-lint

# Lint PR titles and commits for conventional commits format
trigger:
  event:
    - pull_request

steps:
  - name: install-dependencies
    image: node:20-alpine
    commands:
      - npm ci --only=dev

  - name: lint-pr-title
    image: node:20-alpine
    depends_on:
      - install-dependencies
    commands:
      - |
        echo "Validating PR title: ${DRONE_PULL_REQUEST_TITLE}"
        # Check if title follows conventional commits format
        if echo "${DRONE_PULL_REQUEST_TITLE}" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|chore|ci|revert)(\(.+\))?!?:"; then
          echo "✅ PR title follows conventional commits format"
        else
          echo "❌ PR title does not follow conventional commits format"
          echo "Valid formats: feat(scope): description, fix: description, etc."
          exit 1
        fi
    when:
      event:
        - pull_request

  - name: lint-commits
    image: node:20-alpine
    depends_on:
      - install-dependencies
    commands:
      - |
        echo "Linting commits in PR..."
        apk add --no-cache git
        git fetch origin ${DRONE_TARGET_BRANCH}
        # Lint each commit message
        npx commitlint --from origin/${DRONE_TARGET_BRANCH} --to HEAD --verbose
    when:
      event:
        - pull_request

  - name: check-conventional-commits
    image: alpine:latest
    depends_on:
      - lint-commits
    commands:
      - |
        echo "========================================"
        echo "✅ PR Validation Complete"
        echo "========================================"
        echo "PR Title: ${DRONE_PULL_REQUEST_TITLE}"
        echo "All commits follow conventional commits format"
        echo "Valid commit types: feat, fix, docs, style, refactor, perf, test, chore, ci, revert"
        echo "========================================"
    when:
      event:
        - pull_request

  - name: notify-lint-failure
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_chat_id
      message: |
        ❌ PR Lint Failed!

        PR: #${DRONE_PULL_REQUEST}
        Title: ${DRONE_PULL_REQUEST_TITLE}
        Author: {{ commit.author }}

        Please ensure PR title and commits follow conventional commits format.
    when:
      status:
        - failure
      event:
        - pull_request
