---
kind: pipeline
type: docker
name: test

# Run tests on PR creation
trigger:
  event:
    - pull_request

steps:
  - name: install-dependencies
    image: node:20-alpine
    commands:
      - npm ci

  - name: run-tests
    image: node:20-alpine
    commands:
      - npm test

  - name: lint-commits
    image: node:20-alpine
    commands:
      - npx commitlint --from HEAD~1 --to HEAD --verbose

---
kind: pipeline
type: docker
name: build-and-deploy

# Run when PR merged to main or tag created
trigger:
  event:
    - push
    - tag
  branch:
    - main
    - develop

steps:
  - name: install-dependencies
    image: node:20-alpine
    commands:
      - npm ci

  - name: run-tests
    image: node:20-alpine
    commands:
      - npm test

  - name: build-and-copy
    image: alpine:latest
    commands:
      - echo "Building application..."
      # Copy necessary files to deployment directory
      - mkdir -p /tmp/deploy
      - cp -r . /tmp/deploy/
      # Exclude dev files
      - rm -rf /tmp/deploy/node_modules
      - rm -rf /tmp/deploy/.git
      - rm -rf /tmp/deploy/tests
      - echo "Build complete"
    volumes:
      - name: deploy
        path: /tmp/deploy

  - name: copy-to-server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_username
      key:
        from_secret: deploy_ssh_key
      port: 22
      target: /var/www/pulse-server
      source:
        - server.js
        - package.json
        - package-lock.json
        - .env.production
        - ecosystem.config.js
        - routes/**
        - middleware/**
        - services/**
        - utils/**
      strip_components: 0
      overwrite: true
      rm: false
    when:
      branch:
        - main
      event:
        - push
        - tag

  - name: install-production-deps
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_username
      key:
        from_secret: deploy_ssh_key
      port: 22
      script:
        - cd /var/www/pulse-server
        - npm ci --only=production
    when:
      branch:
        - main
      event:
        - push
        - tag

  - name: health-check-before-deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_username
      key:
        from_secret: deploy_ssh_key
      port: 22
      script:
        - echo "Checking server health..."
        - pm2 describe pulse-server || echo "App not running yet"
    when:
      branch:
        - main
      event:
        - push
        - tag

  - name: deploy-with-pm2
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_username
      key:
        from_secret: deploy_ssh_key
      port: 22
      script:
        - cd /var/www/pulse-server
        - pm2 reload ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
        - pm2 save
    when:
      branch:
        - main
      event:
        - push
        - tag

  - name: health-check-after-deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_username
      key:
        from_secret: deploy_ssh_key
      port: 22
      script:
        - sleep 5
        - pm2 describe pulse-server
        - pm2 logs pulse-server --lines 20 --nostream
        # Check if app is responding
        - curl -f http://localhost:3000/health || exit 1
    when:
      branch:
        - main
      event:
        - push
        - tag

  - name: notify-success
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_chat_id
      message: |
        ✅ Deployment successful!

        Repository: {{ repo.name }}
        Branch: {{ commit.branch }}
        Commit: {{ commit.sha }}
        Author: {{ commit.author }}
        Message: {{ commit.message }}
    when:
      status:
        - success
      branch:
        - main
      event:
        - push
        - tag

  - name: notify-failure
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_chat_id
      message: |
        ❌ Deployment failed!

        Repository: {{ repo.name }}
        Branch: {{ commit.branch }}
        Commit: {{ commit.sha }}
        Author: {{ commit.author }}
        Message: {{ commit.message }}
    when:
      status:
        - failure
      branch:
        - main
      event:
        - push
        - tag

volumes:
  - name: deploy
    temp: {}

---
kind: pipeline
type: docker
name: release

# Automatically create release when tag is pushed
trigger:
  event:
    - tag
  ref:
    - refs/tags/v*

steps:
  - name: create-github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      title: "Release ${DRONE_TAG}"
      note: CHANGELOG.md
      files:
        - package.json
        - CHANGELOG.md
    when:
      event:
        - tag

  - name: notify-release
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_chat_id
      message: |
        🚀 New release published!

        Tag: ${DRONE_TAG}
        Repository: {{ repo.name }}
        Author: {{ commit.author }}
    when:
      status:
        - success
      event:
        - tag
